name: JuicyMines
version: '${project.version}'

main: net.juicy.mines.JuicyMinesPlugin
api-version: 1.16

author: Ldoin

dependencies:
  - JuicyAPI

commands:
  juicymines:
    aliases: [ jmines, jm ]