name: JuicyMines
version: '${project.version}'

main: net.juicy.mines.JuicyMinesPlugin

depend:
  - JuicyAPI
  - MultiWorld
api-version: 1.18
author: Ldoin

commands:
  juicymines:
    aliases: [ jmines, jm ]